### ISSUE TITLE
Set up "trading strategy" competition

### ISSUE THREAD

**Issue by Kisgus** [openbot-tech/core#16]
## Tasks included

- [x] Finish documentation #5 #6 #15 and update via tool in #12
- [x] Suggest competition rules & scoop
- [x] Create strategy competition issues, and allocate DAI via Gitcoin
- [x] Promote strategy competition

**Comment by Kisgus** [comment]
**Suggestion: Trend-following Competition Format**

**Duration**
- 1 month

**Markets supported**
- All Bittrex markets

**Indicators supported**
- https://tulipindicators.org/list

**Phase 1**

- External contributors submit a strategy, by using the Strategy_Template and doing a PR to the "Core" repository

**Phase 2**

- The approved strategies are judged by alpha a) backtesting performance (random selection) b) live trading performance (on a chosen market by the strategist)

**Winner Categories**

- 150 DAI for the best "backtesting" performance
- 250 DAI for the best "live trading" performance
